import type { MetadataRoute } from "next";
import { getSiteContent } from "@/lib/sanity/getSiteContent";

export const revalidate = 60;

/**
 * Web app manifest. Modest on purpose — this is a portfolio, not an installable
 * app, so `display: "browser"` keeps it opening as a normal tab rather than
 * claiming standalone-app behaviour it doesn't implement.
 *
 * The icon entry points at /icon, the route generated by icon.tsx.
 */
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const content = await getSiteContent();
  const name = content?.settings?.name ?? "Priyanshu Roy";
  const description =
    content?.settings?.seoDescription ??
    "Brand identity and web development, made together.";

  return {
    name,
    short_name: name.split(" ")[0],
    description,
    start_url: "/",
    display: "browser",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    icons: [
      {
        src: "/icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
